# https://docs.docker.com/compose/overview/#variables-and-moving-a-composition-between-environments
version: "3"

services:
  # https://hub.docker.com/_/redis
  redis:
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./tmp/redis:/data
    ports:
      - "6379:6379"